name: sergievskiyhram

volumes:
  pg_data:
    name: sergievskiy_pg_data
  static:
    name: sergievskiy_static_files

services:
  db:
    image: postgres:latest
    environment:
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_DB=${DB_NAME}
      - PGUSER=${DB_USER}
      - TZ=${TZ}
    volumes:
      - pg_data:/var/lib/postgresql/data/
    expose:
      - "5432"
    healthcheck:
      test:  pg_isready --dbname=$$POSTGRES_DB --username=$$POSTGRES_USER
      interval: 10s
      timeout: 5s
      start_period: 5s
      retries: 5

  app:
    container_name: app
    env_file:
      - ./.env
    build:
      context: .
    command: gunicorn project.wsgi:application --bind 0.0.0.0:8000
    expose:
      - "8000"
    depends_on:
      db:
        condition: service_healthy
    volumes:
      - static:/opt/app/staticfiles
    healthcheck:
      test: [ "CMD-SHELL", "curl http://localhost:8000/admin" ]
      interval: 30s
      timeout: 10s
      retries: 5

  nginx:
    container_name: nginx
    image: nginx:latest
    ports:
      - 80:80
    restart: on-failure
    environment:
      - TZ=${TZ}
    volumes:
      - ./project/deploy/nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./project/deploy/nginx/sites.conf:/etc/nginx/conf.d/sites.conf
      - static:/static/:ro
    depends_on:
      - app
