# Generated by Django 4.2.7 on 2023-12-02 12:44

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('gallery', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='album',
            name='slug',
            field=models.SlugField(blank=True, max_length=255, unique=True, verbose_name='url'),
        ),
        migrations.AlterField(
            model_name='albumimage',
            name='slug',
            field=models.SlugField(blank=True, max_length=255, unique=True, verbose_name='url'),
        ),
        migrations.AlterField(
            model_name='albumvideo',
            name='slug',
            field=models.SlugField(blank=True, max_length=255, unique=True, verbose_name='url'),
        ),
    ]
