# Generated by Django 5.1 on 2024-08-16 20:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                (
                    'id',
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name='ID'
                    ),
                ),
                ('address', models.CharField(max_length=255, verbose_name='Адрес храма')),
                (
                    'mobile_phone',
                    models.CharField(max_length=24, verbose_name='Мобильный телефон'),
                ),
                ('phone', models.CharField(max_length=24, verbose_name='Городской телефон')),
                ('email', models.EmailField(max_length=254, verbose_name='Электронная почта')),
                ('maps', models.TextField()),
            ],
            options={
                'verbose_name': 'Контакты храма',
            },
        ),
    ]
