# Generated by Django 5.0.8 on 2024-08-17 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Clergy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
                ('is_visible', models.BooleanField(default=True, verbose_name='Видимый')),
                ('last_name', models.CharField(max_length=50, verbose_name='Фамилия')),
                ('first_name', models.CharField(max_length=50, verbose_name='Имя')),
                ('middle_name', models.CharField(max_length=50, verbose_name='Отчество')),
                ('birthday', models.DateField(verbose_name='День рождения')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='about/clergy', verbose_name='Фотография')),
                ('rector_temple', models.BooleanField(default=False, verbose_name='Настоятель храма')),
                ('dignity', models.CharField(choices=[('Archdeacon', 'Архидьякон'), ('Archbishop', 'Архиепископ'), ('Archimandrite', 'Архимандрит'), ('Deacon', 'Дьякон'), ('Bishop', 'Епископ'), ('Abbot', 'Игумен'), ('Priest', 'Иерей'), ('Hierodeacon', 'Иеродиакон'), ('Hieromonk', 'Иеромонах'), ('Metropolitan', 'Митрополит'), ('Patriarch', 'Патриарх'), ('Protodeacon', 'Протодьякон'), ('Archpriest', 'Протоиерей'), ('Protopresbyter', 'Протопресвитер')], default='Priest', max_length=50, verbose_name='Сан')),
                ('secular_education', models.CharField(blank=True, max_length=100, null=True, verbose_name='Светское образование')),
                ('spiritual_education', models.CharField(blank=True, max_length=100, null=True, verbose_name='Духовное образование')),
                ('consecrated', models.CharField(blank=True, max_length=20, null=True, verbose_name='Хиротонисан')),
                ('namesake_day', models.CharField(blank=True, max_length=20, null=True, verbose_name='День тезоименитства')),
            ],
            options={
                'verbose_name': 'Духовенство',
                'verbose_name_plural': 'Духовенство',
            },
        ),
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(max_length=255, verbose_name='Адрес храма')),
                ('mobile_phone', models.CharField(max_length=24, verbose_name='Мобильный телефон')),
                ('phone', models.CharField(blank=True, max_length=24, null=True, verbose_name='Городской телефон')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='Электронная почта')),
                ('map', models.TextField(blank=True, help_text='Выбрать или скрипт или изображение! Вставить код карты яндекса, который начинается <script>...</script>. Создать такую можно тут https://yandex.ru/map-constructor', null=True, verbose_name='Скрипт с картой')),
                ('image_map', models.ImageField(blank=True, null=True, upload_to='about/contacts/map', verbose_name='Выбрать или скрипт или изображение! Изображение карты')),
            ],
            options={
                'verbose_name': 'Контакты храма',
            },
        ),
        migrations.CreateModel(
            name='Requisites',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inn', models.CharField(max_length=50, verbose_name='ИНН')),
                ('checkpoint', models.CharField(max_length=50, verbose_name='КПП')),
                ('ogrn', models.CharField(max_length=50, verbose_name='ОГРН')),
                ('okpo', models.CharField(max_length=50, verbose_name='ОКПО')),
                ('current_account', models.CharField(max_length=50, verbose_name='Расчетный счет')),
                ('bank', models.CharField(max_length=255, verbose_name='Банк')),
                ('bic', models.CharField(max_length=50, verbose_name='БИК')),
                ('correspondent_account', models.CharField(max_length=50, verbose_name='Кор. счет')),
                ('name_payee', models.CharField(max_length=255, verbose_name='Наименование получателя платежа')),
                ('purpose_payment', models.CharField(max_length=255, verbose_name='Назначение платежа')),
                ('qr_code', models.ImageField(blank=True, null=True, upload_to='about/qr_codes', verbose_name='QR код')),
            ],
            options={
                'verbose_name': 'Банковские реквизиты',
                'verbose_name_plural': 'Банковские реквизиты',
            },
        ),
    ]
