# Generated by Django 5.1 on 2024-08-16 21:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contact',
            name='maps',
        ),
        migrations.AddField(
            model_name='contact',
            name='image_map',
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to='about/contacts/map',
                verbose_name='Выбрать или скрипт или изображение! Изображение карты',
            ),
        ),
        migrations.AddField(
            model_name='contact',
            name='map',
            field=models.TextField(
                blank=True,
                help_text='Выбрать или скрипт или изображение! Вставить код карты яндекса, который начинается <script>...</script>. Создать такую можно тут https://yandex.ru/map-constructor',
                null=True,
                verbose_name='Скрипт с картой',
            ),
        ),
        migrations.AlterField(
            model_name='contact',
            name='email',
            field=models.EmailField(
                blank=True, max_length=254, null=True, verbose_name='Электронная почта'
            ),
        ),
        migrations.AlterField(
            model_name='contact',
            name='phone',
            field=models.CharField(
                blank=True, max_length=24, null=True, verbose_name='Городской телефон'
            ),
        ),
    ]
