# Generated by Django 5.0.8 on 2024-08-16 22:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0003_requisites'),
    ]

    operations = [
        migrations.AlterField(
            model_name='requisites',
            name='bic',
            field=models.CharField(max_length=50, verbose_name='БИК'),
        ),
        migrations.AlterField(
            model_name='requisites',
            name='checkpoint',
            field=models.CharField(max_length=50, verbose_name='КПП'),
        ),
        migrations.AlterField(
            model_name='requisites',
            name='correspondent_account',
            field=models.CharField(max_length=50, verbose_name='Кор. счет'),
        ),
        migrations.AlterField(
            model_name='requisites',
            name='current_account',
            field=models.CharField(max_length=50, verbose_name='Расчетный счет'),
        ),
        migrations.AlterField(
            model_name='requisites',
            name='inn',
            field=models.CharField(max_length=50, verbose_name='ИНН'),
        ),
        migrations.AlterField(
            model_name='requisites',
            name='ogrn',
            field=models.CharField(max_length=50, verbose_name='ОГРН'),
        ),
        migrations.AlterField(
            model_name='requisites',
            name='okpo',
            field=models.CharField(max_length=50, verbose_name='ОКПО'),
        ),
    ]
