# Generated by Django 5.0.8 on 2024-08-16 23:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0004_alter_requisites_bic_alter_requisites_checkpoint_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='requisites',
            name='qr_code',
            field=models.ImageField(blank=True, null=True, upload_to='about/qr_codes', verbose_name='QR код'),
        ),
    ]
