# Generated by Django 5.0.8 on 2024-08-17 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0005_requisites_qr_code'),
    ]

    operations = [
        migrations.CreateModel(
            name='Clergy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
                ('is_visible', models.BooleanField(default=True, verbose_name='Видимый')),
                ('last_name', models.CharField(max_length=50, verbose_name='Фамилия')),
                ('first_name', models.CharField(max_length=50, verbose_name='Имя')),
                ('middle_name', models.CharField(max_length=50, verbose_name='Отчество')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='about/clergy', verbose_name='Фотография')),
                ('rector_temple', models.BooleanField(default=False, verbose_name='Настоятель храма')),
                ('dignity', models.CharField(choices=[('Archdeacon', 'Архидьякон'), ('Archbishop', 'Архиепископ'), ('Archimandrite', 'Архимандрит'), ('Deacon', 'Дьякон'), ('Bishop', 'Епископ'), ('Abbot', 'Игумен'), ('Priest', 'Иерей'), ('Hierodeacon', 'Иеродиакон'), ('Hieromonk', 'Иеромонах'), ('Metropolitan', 'Митрополит'), ('Patriarch', 'Патриарх'), ('Protodeacon', 'Протодьякон'), ('Archpriest', 'Протоиерей'), ('Protopresbyter', 'Протопресвитер')], default='Priest', max_length=50, verbose_name='Сан')),
                ('secular_education', models.CharField(blank=True, max_length=100, null=True, verbose_name='Светское образование')),
                ('spiritual_education', models.CharField(blank=True, max_length=100, null=True, verbose_name='Духовное образование')),
                ('consecrated', models.DateField(blank=True, null=True, verbose_name='Хиротонисан')),
                ('namesake_day', models.DateField(blank=True, null=True, verbose_name='День тезоименитства')),
            ],
            options={
                'verbose_name': 'Духовенство',
                'verbose_name_plural': 'Духовенство',
            },
        ),
    ]
