# Generated by Django 5.0.8 on 2024-08-17 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0006_clergy'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clergy',
            name='consecrated',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Хиротонисан'),
        ),
        migrations.AlterField(
            model_name='clergy',
            name='namesake_day',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='День тезоименитства'),
        ),
    ]
