# Generated by Django 5.0.8 on 2024-08-17 09:45

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0007_alter_clergy_consecrated_alter_clergy_namesake_day'),
    ]

    operations = [
        migrations.AddField(
            model_name='clergy',
            name='birthday',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='День рождения'),
            preserve_default=False,
        ),
    ]
