upstream app {
    server app:8000;
}

server {
    listen 80 default_server;
    listen [::]:80 default_server;
    server_name _;

    # Статика
    location ^~ /static/ {
        alias /static/;
        expires 30d;
        access_log off;
    }

    # Медиа файлы
    location ^~ /media/ {
        alias /media/;
        expires 30d;
        access_log off;
    }

    # Основной запрос к приложению
    location / {
        proxy_pass http://app;
    }

    # Обработка ошибок
    error_page 404 /404.html;
    error_page 500 502 503 504 /50x.html;

    location = /50x.html {
        root html;
    }
}
