# Generated by Django 5.0.8 on 2024-08-24 12:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name='Day',
            fields=[
                (
                    'id',
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name='ID'
                    ),
                ),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
                ('is_visible', models.BooleanField(default=True, verbose_name='Видимый')),
                ('date', models.DateField(verbose_name='Дата')),
            ],
            options={
                'verbose_name': 'Богослужебный день',
                'verbose_name_plural': 'Богослужебные дни',
            },
        ),
        migrations.CreateModel(
            name='ServiceType',
            fields=[
                (
                    'id',
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name='ID'
                    ),
                ),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
                ('is_visible', models.BooleanField(default=True, verbose_name='Видимый')),
                ('name', models.CharField(verbose_name='Тип службы')),
            ],
            options={
                'verbose_name': 'Тип службы',
                'verbose_name_plural': 'Типы служб',
            },
        ),
        migrations.CreateModel(
            name='Week',
            fields=[
                (
                    'id',
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name='ID'
                    ),
                ),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
                ('is_visible', models.BooleanField(default=True, verbose_name='Видимый')),
                ('name', models.CharField(max_length=100, verbose_name='Название седмицы')),
                (
                    'short_name',
                    models.CharField(
                        blank=True,
                        max_length=100,
                        null=True,
                        verbose_name='Короткое название седмицы',
                    ),
                ),
            ],
            options={
                'verbose_name': 'Седмица',
                'verbose_name_plural': 'Седмицы',
            },
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                (
                    'id',
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name='ID'
                    ),
                ),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
                ('is_visible', models.BooleanField(default=True, verbose_name='Видимый')),
                ('time', models.TimeField(verbose_name='Время')),
                ('to_whom', models.TextField(blank=True, null=True, verbose_name='Кому служба')),
                (
                    'day',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to='schedule.day',
                        verbose_name='День',
                    ),
                ),
                (
                    'type_service',
                    models.ManyToManyField(
                        blank=True, verbose_name='Тип службы', to='schedule.servicetype'
                    ),
                ),
            ],
            options={
                'verbose_name': 'Событие',
                'verbose_name_plural': 'События',
            },
        ),
        migrations.AddField(
            model_name='day',
            name='week',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                to='schedule.week',
                verbose_name='Седмица',
            ),
        ),
    ]
