# Generated by Django 5.0.8 on 2024-08-25 22:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='is_holiday',
        ),
        migrations.AddField(
            model_name='day',
            name='is_holiday',
            field=models.BooleanField(default=False, help_text='Для окраски дня службы в красный', verbose_name='Праздник'),
        ),
    ]
