# Generated by Django 5.0.8 on 2024-09-11 20:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0002_remove_event_is_holiday_day_is_holiday'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='servicetype',
            options={'ordering': ['ordering'], 'verbose_name': 'Тип службы', 'verbose_name_plural': 'Типы служб'},
        ),
        migrations.AddField(
            model_name='servicetype',
            name='ordering',
            field=models.PositiveSmallIntegerField(default=0, verbose_name='Сортировка'),
        ),
    ]
