# Generated by Django 5.0.8 on 2024-10-18 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0003_alter_servicetype_options_servicetype_ordering'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='is_holiday',
            field=models.BooleanField(default=False, help_text='Для окраски дня службы в красный', verbose_name='Праздник'),
        ),
    ]
