# Generated by Django 5.1.2 on 2024-11-18 17:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("schedule", "0004_event_is_holiday"),
    ]

    operations = [
        migrations.AlterField(
            model_name="day",
            name="week",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="days",
                to="schedule.week",
                verbose_name="Седмица",
            ),
        ),
        migrations.AlterField(
            model_name="event",
            name="day",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="events",
                to="schedule.day",
                verbose_name="День",
            ),
        ),
    ]
