# Generated by Django 6.0.6 on 2026-07-08 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0005_alter_day_week_alter_event_day'),
    ]

    operations = [
        migrations.RenameField(
            model_name='event',
            old_name='type_service',
            new_name='service_types',
        ),
        migrations.AlterField(
            model_name='day',
            name='date',
            field=models.DateField(unique=True, verbose_name='Дата'),
        ),
        migrations.AlterField(
            model_name='servicetype',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Тип службы'),
        ),
    ]
