# Generated by Django 4.2.7 on 2023-12-02 12:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name='Album',
            fields=[
                (
                    'id',
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name='ID'
                    ),
                ),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
                ('is_visible', models.BooleanField(default=True, verbose_name='Видимый')),
                ('slug', models.SlugField(max_length=255, verbose_name='url')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='Удален')),
                ('title', models.CharField(max_length=255, verbose_name='Название альбома')),
                ('cover', models.ImageField(upload_to='covers/%Y/%m/%d', verbose_name='Обложка')),
            ],
            options={
                'verbose_name': 'Альбом',
                'verbose_name_plural': 'Альбомы',
            },
        ),
        migrations.CreateModel(
            name='AlbumVideo',
            fields=[
                (
                    'id',
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name='ID'
                    ),
                ),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
                ('is_visible', models.BooleanField(default=True, verbose_name='Видимый')),
                ('slug', models.SlugField(max_length=255, verbose_name='url')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='Удален')),
                ('file', models.FileField(upload_to='videos/%Y/%m/%d', verbose_name='Видео')),
                (
                    'album',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to='gallery.album'
                    ),
                ),
            ],
            options={
                'verbose_name': 'Видео',
                'verbose_name_plural': 'Видео',
            },
        ),
        migrations.CreateModel(
            name='AlbumImage',
            fields=[
                (
                    'id',
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name='ID'
                    ),
                ),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
                ('is_visible', models.BooleanField(default=True, verbose_name='Видимый')),
                ('slug', models.SlugField(max_length=255, verbose_name='url')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='Удален')),
                (
                    'file',
                    models.ImageField(upload_to='images/%Y/%m/%d', verbose_name='Изображение'),
                ),
                (
                    'album',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to='gallery.album'
                    ),
                ),
            ],
            options={
                'verbose_name': 'Изображение',
                'verbose_name_plural': 'Изображения',
            },
        ),
    ]
