# Generated by Django 5.0 on 2023-12-08 22:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('gallery', '0002_alter_album_slug_alter_albumimage_slug_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='albumvideo',
            name='album',
        ),
        migrations.CreateModel(
            name='AlbumContent',
            fields=[
                (
                    'id',
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name='ID'
                    ),
                ),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
                ('is_visible', models.BooleanField(default=True, verbose_name='Видимый')),
                (
                    'slug',
                    models.SlugField(blank=True, max_length=255, unique=True, verbose_name='url'),
                ),
                ('is_deleted', models.BooleanField(default=False, verbose_name='Удален')),
                (
                    'file',
                    models.ImageField(upload_to='images/%Y/%m/%d', verbose_name='Изображение'),
                ),
                (
                    'file_type',
                    models.CharField(
                        choices=[('image', 'Изображение'), ('video', 'Видео')],
                        default='image',
                        max_length=20,
                    ),
                ),
                (
                    'album',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to='gallery.album'
                    ),
                ),
            ],
            options={
                'verbose_name': 'Контент',
                'verbose_name_plural': 'Контент',
            },
        ),
        migrations.DeleteModel(
            name='AlbumImage',
        ),
        migrations.DeleteModel(
            name='AlbumVideo',
        ),
    ]
