# Generated by Django 5.0 on 2023-12-14 14:34

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('gallery', '0003_remove_albumvideo_album_albumcontent_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='albumcontent',
            name='file_type',
            field=models.CharField(
                choices=[('image', 'Изображение'), ('video', 'Видео')],
                default='image',
                max_length=20,
                verbose_name='Тип контента',
            ),
        ),
    ]
