# Generated by Django 5.1.2 on 2024-11-18 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("posts", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="post",
            name="fixed",
            field=models.BooleanField(
                default=False, verbose_name="Закрепленная новость"
            ),
        ),
        migrations.DeleteModel(
            name="FixedPost",
        ),
    ]
