# Generated by Django 5.0.8 on 2024-08-14 18:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_rename_typy_post_post_type_post_post_is_fixed'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='is_fixed',
        ),
        migrations.CreateModel(
            name='FixedPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('target', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='posts.post', verbose_name='Новость')),
            ],
            options={
                'verbose_name': 'Закрепленная новость',
                'verbose_name_plural': 'Закрепленные новости',
            },
        ),
    ]
