name: Telegram Bot Notification

on:
  issues:
    types: [opened]

jobs:
  send-notification:
    runs-on: ubuntu-latest
    steps:
      - name: Send Telegram notification
        uses: appleboy/telegram-action@master
        with:
          to: ${{ secrets.TELEGRAM_CHAT_ID }}
          token: ${{ secrets.TELEGRAM_BOT_TOKEN }}
          message: 'New issue opened: ${{ github.event.issue.html_url }}'

