name: Python Version Compatibility Check

on:
  push:
    branches: [ main ,dev ]
  pull_request:
    branches: [ main, dev ]

jobs:
  check-python-version-compatibility:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.12]
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}

      - name: Check Python version
        run: python --version

